source :gemcutter

# Please keep gem declarations in alphabetical order
gem 'aasm', '2.1.5'
gem 'authlogic', '2.1.2'
gem 'compass', '0.8.17'
gem 'formtastic', '0.9.8'
gem 'haml', '2.2.20'
gem 'hoptoad_notifier', '2.2.6'
gem 'mysql', '2.8.1'
gem 'rails', '2.3.8'

group :test do
  gem 'builder', '2.1.2'
  gem 'caleb-chronic', '0.3.0', :require => 'chronic'
  gem 'codefumes_harvester', '0.1.8'
  gem 'cucumber', '0.7.3'
  gem 'cucumber-rails', '0.3.1'
  gem 'database_cleaner', '0.5.2'
  gem 'diff-lcs', '1.1.2', :require => 'diff/lcs'
  gem 'email_spec', '0.6.2'
  gem 'faker', '0.3.1'
  gem 'flay', '1.3.0'
  gem 'flog', '2.2.0'
  gem 'gherkin', '1.0.30'
  gem 'machinist', '1.0.6'
  gem 'metric_fu', '1.3.0'
  gem 'nokogiri', '1.4.1'
  gem 'polyglot', '0.3.1'
  gem 'rcov', '0.9.8'
  gem 'rspec', '1.3.0'
  gem 'rspec-rails', '1.3.2'
  gem 'ruby_parser', '2.0.4'
  gem 'sexp_processor', '3.0.3'
  gem 'sqlite3-ruby', '1.2.5'
  gem 'term-ansicolor', '1.0.4', :require => 'term/ansicolor'
  gem 'treetop', '1.2.5'
  gem 'trollop', '1.16.2'
  gem 'webrat', '0.7.0'
  gem 'ZenTest', '4.1.3', :require => 'zentest'
end
